import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3a3939",
        "surface-container-low": "#1c1b1b",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#919094",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#d8e2ff",
        "on-error-container": "#ffdad6",
        tertiary: "#c8c6c9",
        "on-secondary": "#303033",
        "tertiary-fixed": "#e4e1e5",
        "tertiary-fixed-dim": "#c8c6c9",
        "on-secondary-container": "#b6b4b8",
        "surface-container-lowest": "#0e0e0e",
        surface: "#131313",
        "on-secondary-fixed-variant": "#47464a",
        "secondary-fixed": "#e4e1e6",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#004395",
        "surface-tint": "#adc6ff",
        "surface-variant": "#353534",
        "primary-container": "#4d8eff",
        "on-primary-fixed": "#001a42",
        error: "#ffb4ab",
        "inverse-on-surface": "#313030",
        "on-error": "#690005",
        secondary: "#c8c5ca",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#c8c5ca",
        "on-primary-container": "#00285d",
        "on-secondary-fixed": "#1b1b1e",
        "on-tertiary-fixed-variant": "#47464a",
        "outline-variant": "#424754",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#29292c",
        "secondary-container": "#47464a",
        "on-background": "#e5e2e1",
        "inverse-primary": "#005ac2",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c2c6d6",
        "on-tertiary": "#303033",
        "on-tertiary-fixed": "#1b1b1e",
        "error-container": "#93000a",
        "on-primary": "#002e6a",
        background: "#131313",
        "surface-container": "#201f1f",
        primary: "#adc6ff",
        outline: "#8c909f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "margin-mobile": "16px",
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "title-md": ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
